In [2]:
import pandas as pd
covid_data= pd.read_csv('E:\covid.csv')
print(covid_data)
print("\nDataset information:")
print(covid_data.info())
print("\nMissing data information:")
print(covid_data.isna().sum())
print()

print('---------------------------------------------------------------------------------------------------')
print('To Get the latest number of confirmed, deaths, recovered and active cases of Novel Coronavirus Country wise')
import pandas as pd
covid_data= pd.read_csv('E:\covid.csv')
covid_data['Active'] = covid_data['Confirmed'] - covid_data['Deaths'] - covid_data['Recovered']
result = covid_data.groupby('Country/Region')['Confirmed', 'Deaths', 'Recovered', 'Active'].sum().reset_index()
print(result) 

print()
print('-------------------------------------------------------------------------------------------------------')
print('To Get Latest number of confirmed deaths and recovered people of Novel Coronavirus cases Country wise')
covid_data= pd.read_csv('E:\covid.csv')
data = covid_data.groupby(['Country/Region', 'Province/State'])['Confirmed', 'Deaths', 'Recovered'].max()
pd.set_option('display.max_rows', None)
print(data)

print()
print('-------------------------------------------------------------------------------------------------------')
print('To Get the Chinese province wise cases of confirmed, deaths and recovered cases of Novel Coronavirus')
covid_data= pd.read_csv('E:\covid.csv')
c_data = covid_data[covid_data['Country/Region']=='China']
c_data = c_data[['Province/State', 'Confirmed', 'Deaths', 'Recovered']]
result = c_data.sort_values(by='Confirmed', ascending=False)
result = result.reset_index(drop=True)
print(result)


print()
print('-------------------------------------------------------------------------------------------------------')
print('To Get the latest country wise deaths cases of Novel Coronavirus')
covid_data= pd.read_csv('E:\covid.csv')
data = covid_data.groupby('Country/Region')['Confirmed', 'Deaths', 'Recovered'].sum().reset_index()
result = data[data['Deaths']>0][['Country/Region', 'Deaths']]
print(result)

print()
print('-------------------------------------------------------------------------------------------------------')
print('to get the List  of countries with no cases of Novel Coronavirus recovered')
covid_data= pd.read_csv('E:\covid.csv')
data = covid_data.groupby('Country/Region')['Confirmed', 'Deaths', 'Recovered'].sum().reset_index()
result = data[data['Recovered']==0][['Country/Region', 'Confirmed', 'Deaths', 'Recovered']]
print(result)

print()
print('List of countries with all cases of Novel Coronavirus died')
print('----------------------------------------------------------------------------------------------------')
covid_data= pd.read_csv('E:\covid.csv')
data = covid_data.groupby('Country/Region')['Confirmed', 'Deaths', 'Recovered'].sum().reset_index()
result = data[data['Confirmed']==data['Deaths']]
result = result[['Country/Region', 'Confirmed', 'Deaths']]
result = result.sort_values('Confirmed', ascending=False)
result = result[result['Confirmed']>0]
result = result.reset_index(drop=True)
print(result)


print()
print('------------------------------------------------------------------------------------------------')
print('List of countries with all cases of Novel Coronavirus recovered')
covid_data= pd.read_csv('E:\covid.csv')
data = covid_data.groupby('Country/Region')['Confirmed', 'Deaths', 'Recovered'].sum().reset_index()
result = data[data['Confirmed']==data['Recovered']]
result = result[['Country/Region', 'Confirmed', 'Recovered']]
result = result.sort_values('Confirmed', ascending=False)
result = result[result['Confirmed']>0]
result = result.reset_index(drop=True)
print(result)


print()
print('----------------------------------------------------------------------------------------------')
print(' To Get the top 10 countries data of Novel Coronavirus')
covid_data= pd.read_csv('E:\covid.csv', usecols = ['Last Update', 'Country/Region', 'Confirmed', 'Deaths', 'Recovered'])
result = covid_data.groupby('Country/Region').max().sort_values(by='Confirmed', ascending=False)[:10]
pd.set_option('display.max_column', None)
print(result)

                   Province/State                    Country/Region  \
0                           Hubei                             China
1                             NaN                             Italy
2                             NaN                              Iran
3                             NaN                             Spain
4                             NaN                           Germany
5                             NaN                      Korea, South
6                          France                            France
7                             NaN                       Switzerland
8                  United Kingdom                    United Kingdom
9                        New York                                US
10                    Netherlands                       Netherlands
11                            NaN                            Norway
12                      Guangdong                             China
13                            NaN                           Austria
14                          Henan                             China
15                            NaN                           Belgium
16                       Zhejiang                             China
17                            NaN                            Sweden
18                     Washington                                US
19                          Hunan                             China
20                          Anhui                             China
21                        Denmark                           Denmark
22                        Jiangxi                             China
23                            NaN                             Japan
24                       Shandong                             China
25                     California                                US
26               Diamond Princess                       Cruise Ship
27                            NaN                          Malaysia
28                        Jiangsu                             China
29                      Chongqing                             China
30                        Sichuan                             China
31                   Heilongjiang                             China
32                        Beijing                             China
33                            NaN                          Portugal
34                            NaN                             Qatar
35                            NaN                           Czechia
36                            NaN                            Greece
37                       Shanghai                             China
38                            NaN                            Israel
39                            NaN                            Brazil
40                            NaN                           Finland
41                          Hebei                             China
42                         Fujian                             China
43                            NaN                          Slovenia
44                     New Jersey                                US
45                            NaN                         Singapore
46                        Guangxi                             China
47                        Shaanxi                             China
48                            NaN                            Poland
49                            NaN                          Pakistan
50                            NaN                           Bahrain
51                            NaN                           Estonia
52                            NaN                           Ireland
53                            NaN                           Iceland
54                  Massachusetts                                US
55                        Florida                                US
56                New South Wales                         Australia
57                            NaN                             Chile
58                            NaN                             Egypt
59                      Louisiana                                US
60                            NaN                       Philippines
61                        Ontario                            Canada
62                            NaN                           Romania
63                            NaN                          Thailand
64                         Yunnan                             China
65                            NaN                         Indonesia
66                            NaN                      Saudi Arabia
67                         Hainan                             China
68                      Hong Kong                             China
69                       Illinois                                US
70                       Colorado                                US
71                            NaN                              Iraq
72                        Guizhou                             China
73                        Georgia                                US
74                            NaN                             India
75                            NaN                        Luxembourg
76                        Tianjin                             China
77                          Gansu                             China
78                         Shanxi                             China
79                            NaN                            Kuwait
80                       Liaoning                             China
81                            NaN                           Lebanon
82                            NaN                              Peru
83                            NaN                            Russia
84                   Pennsylvania                                US
85                          Texas                                US
86                            NaN                        San Marino
87               British Columbia                            Canada
88                            NaN              United Arab Emirates
89                       Victoria                         Australia
90                          Jilin                             China
91                            NaN                            Mexico
92                            NaN                           Armenia
93                     Queensland                         Australia
94                            NaN                           Taiwan*
95                       Xinjiang                             China
96                 Inner Mongolia                             China
97                        Ningxia                             China
98                        Alberta                            Canada
99                         Quebec                            Canada
100                     Tennessee                                US
101                           NaN                          Slovakia
102                     Wisconsin                                US
103                           NaN                            Panama
104                           NaN                         Argentina
105                   Connecticut                                US
106                           NaN                          Bulgaria
107                          Ohio                                US
108                      Virginia                                US
109                        Oregon                                US
110                           NaN                           Vietnam
111                           NaN                          Colombia
112                           NaN                           Croatia
113                           NaN                            Serbia
114                      Michigan                                US
115                North Carolina                                US
116                           NaN                      South Africa
117                           NaN                           Algeria
118                      Maryland                                US
119                     Minnesota                                US
120                           NaN                           Ecuador
121                           NaN                            Brunei
122                        Nevada                                US
123                           NaN                           Albania
124                          Utah                                US
125                           NaN                           Hungary
126                           NaN                            Latvia
127                 Faroe Islands                           Denmark
128                           NaN                            Turkey
129              Diamond Princess                                US
130                South Carolina                                US
131                           NaN                            Cyprus
132                           NaN                         Sri Lanka
133                           NaN                        Costa Rica
134                           NaN                           Andorra
135                       Alabama                                US
136                           NaN                             Malta
137                           NaN                           Morocco
138                           NaN                           Belarus
139                           NaN                           Georgia
140                           NaN                            Jordan
141                           NaN                          Cambodia
142                           NaN                        Kazakhstan
143                           NaN                         Venezuela
144                         Maine                                US
145             Western Australia                         Australia
146                           NaN                           Moldova
147                       Indiana                                US
148               South Australia                         Australia
149                           NaN                           Uruguay
150                           NaN                        Azerbaijan
151                           NaN            Bosnia and Herzegovina
152                           NaN                   North Macedonia
153                           NaN                           Senegal
154                      Kentucky                                US
155                 New Hampshire                                US
156                           NaN                         Lithuania
157                           NaN                              Oman
158                           NaN                           Tunisia
159                          Iowa                                US
160                    New Mexico                                US
161                  Rhode Island                                US
162                           NaN                       Afghanistan
163                      Arkansas                                US
164          District of Columbia                                US
165                           NaN                Dominican Republic
166                Grand Princess                                US
167                   Mississippi                                US
168                      Nebraska                                US
169                       Arizona                                US
170                      Oklahoma                                US
171                       Qinghai                             China
172                           NaN                        Guadeloupe
173                        Kansas                                US
174                           NaN                        Martinique
175                      Delaware                                US
176                           NaN                      Burkina Faso
177                           NaN                           Ukraine
178                           NaN                          Maldives
179                         Macau                             China
180                           NaN                           Jamaica
181                           NaN                       New Zealand
182                       Vermont                                US
183                           NaN                           Bolivia
184                           NaN                     French Guiana
185                      Missouri                                US
186                  South Dakota                                US
187                       Wyoming                                US
188                           NaN                        Bangladesh
189                           NaN                          Cameroon
190                        Hawaii                                US
191                           NaN                        Uzbekistan
192                       Reunion                            France
193                           NaN                          Paraguay
194                           NaN                           Reunion
195                       Montana                                US
196                Grand Princess                            Canada
197                      Manitoba                            Canada
198                 New Brunswick                            Canada
199                           NaN                          Honduras
200                         Idaho                                US
201                      Tasmania                         Australia
202                   Nova Scotia                            Canada
203                  Saskatchewan                            Canada
204                 French Guiana                            France
205                           NaN                             Ghana
206                           NaN                            Guyana
207                           NaN                     Liechtenstein
208                           NaN                            Monaco
209                           NaN                            Rwanda
210                    Guadeloupe                            France
211                           NaN                         Guatemala
212               Channel Islands                    United Kingdom
213                           NaN                     Cote d'Ivoire
214                           NaN                              Cuba
215                           NaN                          Ethiopia
216                           NaN                          Mongolia
217                           NaN               Trinidad and Tobago
218                   Puerto Rico                                US
219                           NaN                        Seychelles
220                           NaN                             Aruba
221     Newfoundland and Labrador                            Canada
222                           NaN                  Congo (Kinshasa)
223              French Polynesia                            France
224              Saint Barthelemy                            France
225                           NaN                              Guam
226                           NaN                             Kenya
227                       Curacao                       Netherlands
228                           NaN                           Nigeria
229                        Alaska                                US
230                          Guam                                US
231                  North Dakota                                US
232                     Gibraltar                    United Kingdom
233  Australian Capital Territory                         Australia
234                           NaN                          Barbados
235                     St Martin                            France
236                           NaN                            Kosovo
237                           NaN                        Montenegro
238                           NaN                           Namibia
239                           NaN                       Saint Lucia
240                Virgin Islands                                US
241                           NaN               Antigua and Barbuda
242            Northern Territory                         Australia
243                           NaN                             Benin
244                           NaN                            Bhutan
245          Prince Edward Island                            Canada
246                           NaN          Central African Republic
247                         Tibet                             China
248                           NaN               Congo (Brazzaville)
249                           NaN                 Equatorial Guinea
250                           NaN                          Eswatini
251                       Mayotte                            France
252                           NaN                             Gabon
253                           NaN                         Greenland
254                           NaN                            Guinea
255                           NaN                          Holy See
256                           NaN                           Liberia
257                           NaN                        Mauritania
258                           NaN                           Mayotte
259                           NaN                             Nepal
260                           NaN  Saint Vincent and the Grenadines
261                           NaN                           Somalia
262                           NaN                             Sudan
263                           NaN                          Suriname
264                           NaN                          Tanzania
265                           NaN                       The Bahamas
266                           NaN                        The Gambia
267                           NaN                              Togo
268                 West Virginia                                US
269                Cayman Islands                    United Kingdom
270         From Diamond Princess                         Australia
271                           NaN                          Guernsey
272                           NaN                            Jersey
273                           NaN                       Puerto Rico
274                           NaN             Republic of the Congo
275                           NaN    occupied Palestinian territory

             Last Update  Confirmed  Deaths  Recovered  Latitude  Longitude
0    2020-03-17T11:53:10      67799    3111      56003   30.9756   112.2707
1    2020-03-17T18:33:02      31506    2503       2941   41.8719    12.5674
2    2020-03-17T15:13:09      16169     988       5389   32.4279    53.6880
3    2020-03-17T20:53:02      11748     533       1028   40.4637    -3.7492
4    2020-03-17T18:53:02       9257      24         67   51.1657    10.4515
5    2020-03-17T10:33:03       8320      81       1407   35.9078   127.7669
6    2020-03-17T19:13:08       7652     148         12   46.2276     2.2137
7    2020-03-17T16:33:04       2700      27          4   46.8182     8.2275
8    2020-03-17T15:13:09       1950      55         52   55.3781    -3.4360
9    2020-03-17T22:53:03       1706      13          0   42.1657   -74.9481
10   2020-03-17T15:13:11       1705      43          2   52.1326     5.2913
11   2020-03-17T19:53:02       1463       3          1   60.4720     8.4689
12   2020-03-17T01:53:03       1364       8       1307   23.3417   113.4244
13   2020-03-17T15:33:06       1332       3          1   47.5162    14.5501

C:\Users\sachin\Anaconda3\lib\site-packages\ipykernel_launcher.py:15: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  from ipykernel import kernelapp as app
C:\Users\sachin\Anaconda3\lib\site-packages\ipykernel_launcher.py:22: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
C:\Users\sachin\Anaconda3\lib\site-packages\ipykernel_launcher.py:41: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
C:\Users\sachin\Anaconda3\lib\site-packages\ipykernel_launcher.py:49: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
C:\Users\sachin\Anaconda3\lib\site-packages\ipykernel_launcher.py:57: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
C:\Users\sachin\Anaconda3\lib\site-packages\ipykernel_launcher.py:70: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.